### ISSUE TITLE
Alimentar database

### ISSUE THREAD

**Issue by EricMGS** [EricMGS/DoctorAche#10]
- [x] Alergias
- [x] Alzheimer's
- [x] Artrites
- [x] Asmas
- [x] Cancer
- [x] Colesterol
- [x] Dores crônicas
- [x] Frio e gripe
- [x] Depressão
- [x] Diabetes
- [x] Digestão
- [x] Visão
- [x] Coração
- [x] Hepatites
- [x] Pressão alta
- [x] HIV
- [x] Doenças infecciosas
- [x] Fígado
- [x] Pulmoes
- [x] Menopausa
- [x] Saúde masculina
- [x] Saúde feminina
- [x] Saúde mental
- [x] Osteoporose
- [x] Enxaqueca
- [x] Pediatricas
- [x] Artrite reumatoide
- [x] Saúde terceira idade
- [x] Pele
- [x] Sono
- [x] Tireóide
- [x] Urologia
- [x] Peso

**Comment by EricMGS** [comment]
Todas as doenças do arquivo dados já estão inseridas

**Comment by EricMGS** [comment]
Galera, infelizmente não vai dar pra usar aqueles arquivos com doenças que vocês fizeram :sob:
Por dois motivos:
- Tá muito fora de padrão
- A maioria das doenças são incomuns

Por isso achei uma forma melhor pra gente resolver isso
Relaxa que dessa vez vai ser bem mais fácil e rápido, é só seguir o Copy and Paste
É só seguir os passos :arrow_double_down: 

## 1 - Preparando
- Abrir o arquivo de texto /database/doencas
- Abrir os seguintes links:
  - [Lista de doenças comuns](https://www.medicinenet.com/diseases_and_conditions/article.htm)
  - [Deus Google](https://google.com.br)

## 2 -   Escolhendo
- No site [Lista de doenças comuns](https://www.medicinenet.com/diseases_and_conditions/article.htm) escolher um dos tipos de doenças
  - **Confira antes se já não foi feito**

![selecionando_tema](https://user-images.githubusercontent.com/37462627/47932092-78ac4900-deaf-11e8-9fe7-1c8e346caeaf.png)
Como exemplo vou usar o tema alergia e a doença alergia a látex

## 3 - Buscando
- No [tio Google](https://google.com.br) pesquisar as doenças que tem nessa categoria
![pesquisando](https://user-images.githubusercontent.com/37462627/47932218-ce80f100-deaf-11e8-8276-f58ec93fb7a3.png)

## 4 - Pegando informações
- As informações que você vai usar são as do box a direita
  - Nome da doença
  - Número de casos
  - Sintomas

![informacoes1](https://user-images.githubusercontent.com/37462627/47932348-24559900-deb0-11e8-8d37-e9d0adb907a0.png)
![informacoes2](https://user-images.githubusercontent.com/37462627/47932355-291a4d00-deb0-11e8-9f75-ea3db856e762.png)

## 5 - Ctrl C Ctrl V e se der merda Ctrl Z

![modelo](https://user-images.githubusercontent.com/37462627/47932505-a2b23b00-deb0-11e8-8f2f-d20917dab172.png)

Só seguir o modelo da imagem
Porém...
**Não esquece do padrão**

--------------------------------- (Pelo menos 3 traços)
#NOME    
[nome da doença aqui] (primeira letra minúscula e sem espaço no fim)
#CASOS 
[número de casos aqui] (no [parceiro Google](https://www.google.com.br) o número tá abreviado, mas coloquem o número inteiro, sem errar na quantidade de zeros)
#SINTOMAS 
[lista de sintomas aqui]
- essa parte é a mais diferenciada
  - cada sintoma em uma linha
  - não mudar do jeito que está escrito no [senhor Google](https://www.google.com.br)
  - tudo minúsculo
  - sem espaço no final
  - se estiver por exemplo: ```Na pele: erupções ou vermelhidão```,  deixe ```erupções, vermelhidão na pele``` (uma em cada linha, que nem na foto)

## E é isso!

**Comment by EricMGS** [comment]
fazendo artrites

**Comment by a-men-o** [comment]
fazendo depressao

**Comment by EricMGS** [comment]
> fazendo depressao

@a-men-o vc marcou a  caixinha lá em cima, já concluiu?

**Comment by EricMGS** [comment]
fazendo colesterol

**Comment by a-men-o** [comment]
fazendo visao

**Comment by EricMGS** [comment]
fazendo frio e gripe

**Comment by EricMGS** [comment]
fazendo diabetes

**Comment by EricMGS** [comment]
fazendo digestão

**Comment by Italouu123** [comment]
Fazendo coração

**Comment by EricMGS** [comment]
fazendo hepatites

**Comment by a-men-o** [comment]
fazendo pediatricas

**Comment by EricMGS** [comment]
> fazendo pediatricas

visão tá pronto?

**Comment by Italouu123** [comment]
> > fazendo pediatricas
> 
> visão tá pronto?

Visão ainda não

**Comment by OtavioAraujo** [comment]
Fazendo Pressão alta

**Comment by EricMGS** [comment]
fazendo pressão alta

**Comment by a-men-o** [comment]
visão ta pronto sim


> > > fazendo pediatricas
> > 
> > 
> > visão tá pronto?
> 
> Visão ainda não

visão ta pronto sim

**Comment by OtavioAraujo** [comment]
Fazendo Peso

**Comment by GuilLazarini** [comment]
Fazendo Doenças infecciosas

**Comment by EricMGS** [comment]
fazendo menopausa

> Fazendo Pressão alta

maus não tinha visto e acabei fazendo

**Comment by EricMGS** [comment]
galera acho melhor marcar o quadradinho lá na hora que começar e não na hora que terminar

**Comment by EricMGS** [comment]
> fazendo menopausa
> 
> > Fazendo Pressão alta
> 
> maus não tinha visto e acabei fazendo

bugou, ah fodase

**Comment by a-men-o** [comment]
fazendo sono

**Comment by EricMGS** [comment]
fazendo osteoporose

**Comment by Italouu123** [comment]
fazendo Enxaqueca

**Comment by GuilLazarini** [comment]
fazendo Saúde mental

**Comment by a-men-o** [comment]
fazendo pele

**Comment by Italouu123** [comment]
Fazendo Saúde masculina

**Comment by GuilLazarini** [comment]
fazendo Tireóide

**Comment by Italouu123** [comment]
Fazendo Saúde feminina

**Comment by Italouu123** [comment]
fazendo Artrite reumatoide

**Comment by Italouu123** [comment]
fazendo Saúde terceira idade
